# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81ea043439a1398ff7c9debd7b3e839d16f102e61befcf8b26129f7955729878e8ba4c5a890d90e8ea381f218ccba75c97685bc2d6e55ba5170b251ae74f4bb

test:
  secret_key_base: 8a32df57635b51319a3caa1f23dc083f2aef3d3a18fb618c6e121fe92632ba68d5cfefddcd059614b6fe3fe93e9c28e76071726f3a01c63f8abea6263a0e8092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
